language: cpp

before_install:    
    # Define TRAVIS variable for workarounds
    - export CXXFLAGS="$CXXFLAGS -DTRAVIS"
    
    # Upgrade gcc
    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    - sudo apt-get -qq update 
    - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.8; fi
    - if [ "$CXX" = "g++" ]; then sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 98; fi
    - if [ "$CXX" = "clang++" ]; then export CXXFLAGS="$CXXFLAGS -stdlib=libc++"
    
    # Install dependencies
    - sudo apt-get -qq install libwxgtk3.0-dev libwxgtk3.0-0 libssh2-1-dev

# Build with both gcc and clang
compiler:
    - gcc
    - clang

script: make clean run-tests
