language: cpp

before_install:    
    # Define TRAVIS variable for workarounds
    - export CXXFLAGS="$CXXFLAGS -DTRAVIS"

install:
    - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8"; fi

# Build with both gcc and clang
compiler:
    - gcc
    - clang
    
addons:
    apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - libwxgtk3.0-dev
        - libwxgtk3.0-0
        - libssh2-1-dev
        - gcc-4.8
        - g++-4.8
        - clang

script: make clean run-tests
