language: cpp

before_install:
    # Setup virtual x server for gui testing
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    # Install dependencies
    - sudo apt-get update -qq
    - sudo apt-get install -qq libwxgtk3.0-dev libwxgtk3.0-0 libssh2-1-dev

# Build with both gcc and clang
compiler:
    - gcc
    - clang

script: make
