sudo: false
language: cpp

before_install:    
    # Define TRAVIS variable for workarounds
    - export CXXFLAGS="$CXXFLAGS -DTRAVIS"
    - sudo apt-get -qq update
    
    # Install dependencies
    - sudo apt-get -qq install libwxgtk3.0-dev libwxgtk3.0-0 libssh2-1-dev

install:
    - if [ "$CXX" = "g++" ]; then sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 98; fi

# Build with both gcc and clang
compiler:
    - gcc
    - clang
    
addons:
    apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - gcc-4.8
        - g++-4.8
        - clang

script: make clean run-tests
