sudo: required
dist: trusty
language: cpp

before_install:
    # Define TRAVIS variable for workarounds
    - export CXXFLAGS="$CXXFLAGS -DTRAVIS"

install:
    - if [ "$CXX" = "g++" ]; then sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 98; fi

# Build with both gcc and clang
compiler:
    - gcc
    - clang

addons:
    apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - cmake
        - gcc-4.8
        - g++-4.8
        - clang
        - libgtk2.0-dev

script: make clean run-tests
